const cfg=window.O2_CONFIG||{}; const configured=!!(cfg.SUPABASE_URL&&cfg.SUPABASE_ANON_KEY); const sb=configured?window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY):null;
const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const CATS={choreography:['Choreo Memorisation','c1'],cleaning:['Details / Cleaning','c2'],dynamics:['Dynamics','c3'],isolations:['Isolations','c4'],expressions:['Facial Expressions','c5'],stamina:['Stamina','c6'],foundation:['Foundation','c7'],formation:['Formation Revision','c8']};
let state={user:null,profile:null,group:null,role:'member',entries:[],homework:[],members:[],tab:'feed'};
const demoEntries=[{id:'d1',display_name:'Hanny',duration_minutes:150,description:'Worked on the chorus and transition into the dance break. Repeated the formation change slowly, then brought it back to full speed.',improvements:'Cleaner arm lines and much better timing in the second chorus.',challenges:'Keep stamina consistent through the final section.',categories:['choreography','cleaning','dynamics','formation'],created_at:new Date().toISOString(),homework_completed:true,reactions:12,comments:3},{id:'d2',display_name:'Jiwoo',duration_minutes:95,description:'Focused on pre-chorus isolations and foundation drills before running the whole piece twice.',improvements:'Chest isolations feel more controlled.',challenges:'Facial expressions drop when concentrating on details.',categories:['isolations','foundation','expressions'],created_at:new Date(Date.now()-86400000).toISOString(),homework_completed:false,reactions:7,comments:1}];
const demoHW=[{id:'h1',title:'Send practice video to teacher',due_date:new Date(Date.now()+3*86400000).toISOString().slice(0,10),completed:false}];

function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function fmtMin(m){return `${Math.floor(m/60)?Math.floor(m/60)+'h ':''}${m%60?m%60+'m':''}`.trim()||'0m'}
function toast(t){let e=document.createElement('div');e.className='toast';e.textContent=t;document.body.append(e);setTimeout(()=>e.remove(),2200)}

async function boot(){
 if(sb){const {data}=await sb.auth.getSession(); state.user=data.session?.user||null; sb.auth.onAuthStateChange((_e,s)=>{state.user=s?.user||null; refresh()});}
 await refresh();
}
async function refresh(){
 if(!configured){state.entries=demoEntries;state.homework=demoHW;render();return}
 if(!state.user){state.group=null;state.entries=[];state.homework=[];render();return}
 const {data:p}=await sb.from('profiles').select('*').eq('id',state.user.id).maybeSingle();state.profile=p;
 const {data:gm}=await sb.from('group_members').select('group_id,role,groups(id,name,invite_code)').eq('user_id',state.user.id).limit(1).maybeSingle();
 if(gm){state.group=gm.groups;state.role=gm.role;await loadGroup()} else {state.group=null;state.entries=[];state.homework=[];state.members=[]}
 render();
}
async function loadGroup(){
 if(!sb||!state.group)return;
 const gid=state.group.id;
 const [{data:ents},{data:hws},{data:members},{data:comps},{data:reacts},{data:comments}]=await Promise.all([
  sb.from('practice_entries').select('*').eq('group_id',gid).order('created_at',{ascending:false}),
  sb.from('homework').select('*').eq('group_id',gid).order('due_date'),
  sb.from('group_members').select('user_id,role').eq('group_id',gid),
  sb.from('homework_completion').select('*').eq('user_id',state.user.id),
  sb.from('reactions').select('entry_id'),sb.from('comments').select('entry_id')
 ]);
 const ids=[...new Set([...(ents||[]).map(x=>x.user_id),...(members||[]).map(x=>x.user_id)])]; let pmap={}; if(ids.length){const {data:ps}=await sb.from('profiles').select('*').in('id',ids);(ps||[]).forEach(p=>pmap[p.id]=p)}
 state.entries=(ents||[]).map(e=>({...e,display_name:pmap[e.user_id]?.display_name||'Member',reactions:(reacts||[]).filter(r=>r.entry_id===e.id).length,comments:(comments||[]).filter(c=>c.entry_id===e.id).length}));
 state.homework=(hws||[]).map(h=>({...h,completed:(comps||[]).some(c=>c.homework_id===h.id&&c.completed_at)}));
 state.members=(members||[]).map(m=>({...m,display_name:pmap[m.user_id]?.display_name||'Member'}));
}

function render(){
 const app=$('#app'); app.innerHTML=`<main class="shell"><aside class="sidebar"><div class="brand"><img src="assets/o2-logo.png"><span>Practice Journal</span></div>${state.group?`<div class="groupPill"><span class="dot"></span>${esc(state.group.name)}</div>`:''}<nav>${nav('feed','⌂','Feed')}${nav('journal','▤','My Journal')}${nav('homework','□','Homework')}${nav('stats','▥','Stats')}${nav('members','♙','Members')}</nav><div class="sideBottom">${state.user?`<button id="signout" class="ghost">↪ Sign out</button>`:`<button id="signin" class="login">Sign in</button>`}</div></aside><section class="content"><header class="topbar"><div><p class="eyebrow">O2 STUDIOS</p><h1>${title()}</h1></div>${state.group?`<button id="newEntry" class="primary">＋ New Entry</button>`:''}</header>${!configured?`<div class="setupBanner"><b>Demo mode.</b> The interface works now, but shared accounts need Supabase. Setup instructions are in README.md.</div>`:''}${configured&&state.user&&!state.group?groupSetup():configured&&!state.user?welcome():view()}</section></main><div id="modal"></div>`;
 bind();
}
function nav(k,i,t){return `<button class="nav ${state.tab===k?'active':''}" data-tab="${k}"><span>${i}</span><label>${t}</label></button>`}
function title(){return ({feed:'Practice Feed',journal:'My Journal',homework:'Homework',stats:'Stats',members:'Members'})[state.tab]}
function welcome(){return `<section class="empty"><img src="assets/o2-logo.png"><h2>O2 Practice Journal</h2><p>Sign in to join your dance group, post practice entries and track your progress together.</p><button class="primary" id="signin2">Sign in / create account</button></section>`}
function groupSetup(){return `<section class="empty"><h2>Join your O2 group</h2><p>Create a group for your team or enter an invite code from another member.</p><div class="joinGrid"><button class="primary" id="createGroup">Create group</button><button class="secondary" id="joinGroup">Join with code</button></div></section>`}
function view(){if(state.tab==='feed')return feed();if(state.tab==='journal')return journal();if(state.tab==='homework')return homeworkView();if(state.tab==='stats')return stats();return membersView()}
function feed(){return `<div class="grid"><div class="feed">${state.entries.length?state.entries.map(entryCard).join(''):'<div class="emptyCard">No practice entries yet. Be first 👀</div>'}</div><aside class="rightcol">${homeworkPanel()}${leader()}</aside></div>`}
function entryCard(e){return `<article class="entryCard"><div class="entryHead"><div class="avatar">${esc((e.display_name||'M')[0])}</div><div><strong>${esc(e.display_name)}</strong><span>${new Date(e.created_at).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</span></div><div class="duration">◷ ${fmtMin(e.duration_minutes)}</div></div><div class="flairs">${(e.categories||[]).map(c=>`<span class="flair ${CATS[c]?.[1]||''}">${esc(CATS[c]?.[0]||c)}</span>`).join('')}</div><p class="desc">${esc(e.description)}</p><div class="split"><div><small>IMPROVEMENTS</small><p>${esc(e.improvements||'—')}</p></div><div><small>CHALLENGES</small><p>${esc(e.challenges||'—')}</p></div></div><div class="entryFoot"><span class="${e.homework_completed?'done':'pending'}">✓ Homework ${e.homework_completed?'completed':'pending'}</span><div class="social"><button class="react" data-id="${e.id}">🔥 ${e.reactions||0}</button><button class="comment" data-id="${e.id}">▢ ${e.comments||0}</button></div></div></article>`}
function homeworkPanel(){return `<section class="panel"><div class="panelTitle"><b>Homework</b>${state.user?'<button id="addHomework">+ Add</button>':''}</div>${state.homework.length?state.homework.slice(0,4).map(h=>`<label class="hw"><input class="hwcheck" data-id="${h.id}" type="checkbox" ${h.completed?'checked':''}><span><strong>${esc(h.title)}</strong><small>Due ${new Date(h.due_date+'T00:00:00').toLocaleDateString()}</small></span></label>`).join(''):'<p class="muted">Nothing due.</p>'}</section>`}
function leader(){let s={};state.entries.forEach(e=>s[e.display_name]=(s[e.display_name]||0)+e.duration_minutes);return `<section class="panel"><div class="panelTitle"><b>This week</b></div>${Object.entries(s).sort((a,b)=>b[1]-a[1]).slice(0,5).map(([n,m],i)=>`<div class="rank"><span>${i+1}</span><b>${esc(n)}</b><em>${(m/60).toFixed(1)}h</em></div>`).join('')}</section>`}
function journal(){let mine=state.entries.filter(e=>!configured||e.user_id===state.user?.id);let mins=mine.reduce((a,b)=>a+b.duration_minutes,0);return `<div class="single"><div class="metricRow">${metric('Entries',mine.length)}${metric('Practice time',(mins/60).toFixed(1)+'h')}${metric('Current streak',streak(mine)+' days')}</div><div class="feed">${mine.map(entryCard).join('')||'<div class="emptyCard">Your journal is empty.</div>'}</div></div>`}
function homeworkView(){return `<div class="single"><div class="sectionHead"><h2>Weekly Homework</h2><button class="secondary" id="addHomework">＋ Add homework</button></div>${state.homework.map(h=>`<div class="homeworkRow"><input class="hwcheck" data-id="${h.id}" type="checkbox" ${h.completed?'checked':''}><div><b>${esc(h.title)}</b><span>Due ${new Date(h.due_date+'T00:00:00').toLocaleDateString()}</span></div><em>${h.completed?'Complete':'To do'}</em></div>`).join('')||'<div class="emptyCard">No homework has been added.</div>'}</div>`}
function metric(l,v){return `<div class="metric"><small>${l}</small><strong>${v}</strong></div>`}
function streak(es){let days=new Set(es.map(e=>new Date(e.created_at).toDateString())),n=0,d=new Date();while(days.has(d.toDateString())){n++;d.setDate(d.getDate()-1)}return n}
function stats(){let mins=state.entries.reduce((a,b)=>a+b.duration_minutes,0),done=state.homework.filter(h=>h.completed).length,comp=state.homework.length?Math.round(done/state.homework.length*100):0;let recent=[...state.entries].slice(0,12).reverse();let max=Math.max(1,...recent.map(e=>e.duration_minutes));return `<div class="single"><div class="metricRow">${metric('Total practice',(mins/60).toFixed(1)+'h')}${metric('Homework',comp+'%')}${metric('Practice streak',streak(state.entries)+' days')}</div><section class="chartCard"><p class="eyebrow">PRACTICE TIME</p><h2>Recent sessions</h2><div class="bars">${recent.map((e,i)=>`<div><span style="height:${Math.max(8,e.duration_minutes/max*100)}%"></span><small>${i+1}</small></div>`).join('')}</div></section><section class="chartCard"><p class="eyebrow">CATEGORY FOCUS</p><div class="categoryStats">${Object.entries(CATS).map(([k,v])=>{let n=state.entries.filter(e=>(e.categories||[]).includes(k)).length;return `<div><span>${v[0]}</span><div><i style="width:${Math.min(100,n*20)}%"></i></div><b>${n}</b></div>`}).join('')}</div></section></div>`}
function membersView(){let mem=state.members.length?state.members:[...new Set(state.entries.map(e=>e.display_name))].map((n,i)=>({display_name:n,role:i?'member':'admin'}));return `<div class="memberGrid">${mem.map(m=>`<div class="memberCard"><div class="avatar large">${esc(m.display_name[0])}</div><h3>${esc(m.display_name)}</h3><p>${esc(m.role||'member')}</p></div>`).join('')}<div class="memberCard invite"><b>Invite code</b><strong>${esc(state.group?.invite_code||'O2-7K4P')}</strong><button id="copyCode">Copy</button></div></div>`}

function bind(){
 $$('.nav').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;render()}); $('#signin')?.addEventListener('click',authModal);$('#signin2')?.addEventListener('click',authModal);$('#signout')?.addEventListener('click',async()=>{await sb.auth.signOut()});$('#newEntry')?.addEventListener('click',entryModal);$('#createGroup')?.addEventListener('click',createGroupModal);$('#joinGroup')?.addEventListener('click',joinGroupModal);$$('#addHomework').forEach(b=>b.addEventListener('click',homeworkModal));$$('.hwcheck').forEach(x=>x.onchange=()=>toggleHW(x.dataset.id,x.checked));$$('.react').forEach(b=>b.onclick=()=>react(b.dataset.id));$$('.comment').forEach(b=>b.onclick=()=>commentModal(b.dataset.id));$('#copyCode')?.addEventListener('click',()=>{navigator.clipboard.writeText(state.group.invite_code);toast('Invite code copied')})
}
function modal(html){$('#modal').innerHTML=`<div class="overlay"><div class="modal">${html}</div></div>`;$('.close')?.addEventListener('click',()=>$('#modal').innerHTML='')}
function authModal(){modal(`<button class="close">×</button><p class="eyebrow">O2 ACCOUNT</p><h2>Sign in</h2><label>Name <span class="onlySignup">(for new accounts)</span><input id="aname"></label><label>Email<input id="aemail" type="email"></label><label>Password<input id="apass" type="password"></label><div class="twoBtns"><button id="loginGo" class="primary">Sign in</button><button id="signupGo" class="secondary">Create account</button></div><p id="amsg" class="muted"></p>`);$('#loginGo').onclick=async()=>{if(!sb)return;let {error}=await sb.auth.signInWithPassword({email:$('#aemail').value,password:$('#apass').value});$('#amsg').textContent=error?.message||'Signed in';if(!error){$('#modal').innerHTML='';refresh()}};$('#signupGo').onclick=async()=>{if(!sb)return;let {error}=await sb.auth.signUp({email:$('#aemail').value,password:$('#apass').value,options:{data:{display_name:$('#aname').value||$('#aemail').value.split('@')[0]}}});$('#amsg').textContent=error?.message||'Account created. Check your email if confirmation is enabled.'}}
function createGroupModal(){modal(`<button class="close">×</button><p class="eyebrow">NEW GROUP</p><h2>Create your team</h2><label>Group name<input id="gname" placeholder="O2 Team A"></label><button id="gcreate" class="primary wide">Create group</button>`);$('#gcreate').onclick=async()=>{let name=$('#gname').value.trim();if(!name)return;let {data:g,error}=await sb.from('groups').insert({name,created_by:state.user.id}).select().single();if(error)return toast(error.message);await sb.from('group_members').insert({group_id:g.id,user_id:state.user.id,role:'admin'});$('#modal').innerHTML='';refresh()}}
function joinGroupModal(){modal(`<button class="close">×</button><p class="eyebrow">JOIN GROUP</p><h2>Enter invite code</h2><label>Invite code<input id="gcode" placeholder="O2-7K4P"></label><button id="gjoin" class="primary wide">Join group</button>`);$('#gjoin').onclick=async()=>{let code=$('#gcode').value.trim().toUpperCase();let {data:g,error}=await sb.from('groups').select('*').eq('invite_code',code).maybeSingle();if(error||!g)return toast('Group not found');let r=await sb.from('group_members').insert({group_id:g.id,user_id:state.user.id,role:'member'});if(r.error)return toast(r.error.message);$('#modal').innerHTML='';refresh()}}
function entryModal(){modal(`<button class="close">×</button><p class="eyebrow">NEW PRACTICE ENTRY</p><h2>Log today’s practice</h2><label>Practice duration (minutes)<input id="duration" type="number" value="60"></label><label>What did you work on?</label><div class="selectFlairs">${Object.entries(CATS).map(([k,v])=>`<button class="flair ${v[1]}" data-cat="${k}">${v[0]}</button>`).join('')}</div><label>What did you actually work on?<textarea id="description" placeholder="Describe the session…"></textarea></label><div class="two"><label>Improvements<textarea id="improvements"></textarea></label><label>Challenges to overcome<textarea id="challenges"></textarea></label></div><label class="check"><input id="hwdone" type="checkbox"> I completed this week’s homework</label><button id="publish" class="primary wide">Publish entry</button>`);let selected=[];$$('.selectFlairs .flair').forEach(b=>b.onclick=()=>{let c=b.dataset.cat;b.classList.toggle('selected');selected=selected.includes(c)?selected.filter(x=>x!==c):[...selected,c]});$('#publish').onclick=async()=>{let item={user_id:state.user.id,group_id:state.group.id,duration_minutes:+$('#duration').value||0,description:$('#description').value,improvements:$('#improvements').value,challenges:$('#challenges').value,categories:selected,homework_completed:$('#hwdone').checked};let {error}=await sb.from('practice_entries').insert(item);if(error)return toast(error.message);$('#modal').innerHTML='';toast('Practice entry published');await loadGroup();render()}}
function homeworkModal(){modal(`<button class="close">×</button><p class="eyebrow">GROUP HOMEWORK</p><h2>Add homework</h2><label>Task<input id="htitle" placeholder="Send practice video to teacher"></label><label>Due date<input id="hdate" type="date"></label><button id="hadd" class="primary wide">Add for everyone</button>`);$('#hadd').onclick=async()=>{let {error}=await sb.from('homework').insert({group_id:state.group.id,title:$('#htitle').value,due_date:$('#hdate').value,created_by:state.user.id});if(error)return toast(error.message);$('#modal').innerHTML='';await loadGroup();render()}}
async function toggleHW(id,done){if(!sb)return; if(done) await sb.from('homework_completion').upsert({homework_id:id,user_id:state.user.id,completed_at:new Date().toISOString()}); else await sb.from('homework_completion').delete().eq('homework_id',id).eq('user_id',state.user.id);await loadGroup();render()}
async function react(id){if(!sb)return toast('Reactions are live after Supabase setup');let {error}=await sb.from('reactions').insert({entry_id:id,user_id:state.user.id,emoji:'🔥'});if(error){await sb.from('reactions').delete().eq('entry_id',id).eq('user_id',state.user.id).eq('emoji','🔥')}await loadGroup();render()}
function commentModal(id){if(!sb)return toast('Comments are live after Supabase setup');modal(`<button class="close">×</button><p class="eyebrow">COMMENT</p><h2>Add a comment</h2><textarea id="commentBody" placeholder="Write something supportive…"></textarea><button id="commentGo" class="primary wide">Post comment</button>`);$('#commentGo').onclick=async()=>{let body=$('#commentBody').value.trim();if(!body)return;let {error}=await sb.from('comments').insert({entry_id:id,user_id:state.user.id,body});if(error)return toast(error.message);$('#modal').innerHTML='';await loadGroup();render()}}
boot();
