const cfg=window.O2_CONFIG||{}; const configured=!!(cfg.SUPABASE_URL&&cfg.SUPABASE_ANON_KEY);
const TOKEN_KEY='o2_session_token'; const USER_KEY='o2_session_user';
const getToken=()=>localStorage.getItem(TOKEN_KEY)||'';
const sb=configured?window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY):null;
const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const CATS={choreography:['Choreo Memorisation','c1'],cleaning:['Details / Cleaning','c2'],dynamics:['Dynamics','c3'],isolations:['Isolations','c4'],expressions:['Facial Expressions','c5'],stamina:['Stamina','c6'],foundation:['Foundation','c7'],formation:['Formation Revision','c8']};
let state={user:null,group:null,role:'member',entries:[],homework:[],members:[],tab:'feed'};
const demoEntries=[{id:'d1',display_name:'Hanny',duration_minutes:150,description:'Worked on the chorus and transition into the dance break. Repeated the formation change slowly, then brought it back to full speed.',improvements:'Cleaner arm lines and much better timing in the second chorus.',challenges:'Keep stamina consistent through the final section.',categories:['choreography','cleaning','dynamics','formation'],created_at:new Date().toISOString(),homework_completed:true,reactions:12,comments:3},{id:'d2',display_name:'Jiwoo',duration_minutes:95,description:'Focused on pre-chorus isolations and foundation drills before running the whole piece twice.',improvements:'Chest isolations feel more controlled.',challenges:'Facial expressions drop when concentrating on details.',categories:['isolations','foundation','expressions'],created_at:new Date(Date.now()-86400000).toISOString(),homework_completed:false,reactions:7,comments:1}];
const demoHW=[{id:'h1',title:'Send practice video to teacher',due_date:new Date(Date.now()+3*86400000).toISOString().slice(0,10),completed:false}];
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function fmtMin(m){return `${Math.floor(m/60)?Math.floor(m/60)+'h ':''}${m%60?m%60+'m':''}`.trim()||'0m'}
function toast(t){let e=document.createElement('div');e.className='toast';e.textContent=t;document.body.append(e);setTimeout(()=>e.remove(),2600)}
async function rpc(name,args={}){if(!sb)throw new Error('Supabase is not configured.');const {data,error}=await sb.rpc(name,args);if(error)throw new Error(error.message.replace(/^.*?: /,''));return data}
function cachedUser(){try{return JSON.parse(localStorage.getItem(USER_KEY)||'null')}catch{return null}}
async function boot(){state.user=cachedUser();await refresh()}
async function refresh(){
 if(!configured){state.entries=demoEntries;state.homework=demoHW;render();return}
 if(!getToken()){state.user=null;state.group=null;state.entries=[];state.homework=[];state.members=[];render();return}
 try{const d=await rpc('o2_dashboard',{p_token:getToken()});if(!d?.authenticated){clearSession();render();return}state.user=d.user;localStorage.setItem(USER_KEY,JSON.stringify(d.user));state.group=d.group;state.role=d.group?.role||'member';state.entries=d.entries||[];state.homework=d.homework||[];state.members=d.members||[];render()}catch(e){toast(e.message);render()}
}
function clearSession(){localStorage.removeItem(TOKEN_KEY);localStorage.removeItem(USER_KEY);state.user=null;state.group=null;state.entries=[];state.homework=[];state.members=[]}
function render(){const app=$('#app');app.innerHTML=`<main class="shell"><aside class="sidebar"><div class="brand"><img src="assets/o2-logo.png"><span>Practice Journal</span></div>${state.group?`<div class="groupPill"><span class="dot"></span>${esc(state.group.name)}</div>`:''}<nav>${nav('feed','⌂','Feed')}${nav('journal','▤','My Journal')}${nav('homework','□','Homework')}${nav('stats','▥','Stats')}${nav('members','♙','Members')}</nav><div class="sideBottom">${state.user?`<button id="signout" class="ghost">↪ Sign out</button>`:`<button id="signin" class="login">Sign in</button>`}</div></aside><section class="content"><header class="topbar"><div><p class="eyebrow">O2 STUDIOS</p><h1>${title()}</h1></div>${state.group?`<button id="newEntry" class="primary">＋ New Entry</button>`:''}</header>${!configured?`<div class="setupBanner"><b>Demo mode.</b> Add your Supabase URL + anon key to config.js, then run static-auth-migration.sql.</div>`:''}${configured&&state.user&&!state.group?groupSetup():configured&&!state.user?welcome():view()}</section></main><div id="modal"></div>`;bind()}
function nav(k,i,t){return `<button class="nav ${state.tab===k?'active':''}" data-tab="${k}"><span>${i}</span><label>${t}</label></button>`}
function title(){return ({feed:'Practice Feed',journal:'My Journal',homework:'Homework',stats:'Stats',members:'Members'})[state.tab]}
function welcome(){return `<section class="empty"><img src="assets/o2-logo.png"><h2>O2 Practice Journal</h2><p>Sign in with your O2 username. No email address is used.</p><button class="primary" id="signin2">Sign in / create account</button></section>`}
function groupSetup(){return `<section class="empty"><h2>Join your O2 group</h2><p>Create a group for your team or enter an invite code from another member.</p><div class="joinGrid"><button class="primary" id="createGroup">Create group</button><button class="secondary" id="joinGroup">Join with code</button></div></section>`}
function view(){if(state.tab==='feed')return feed();if(state.tab==='journal')return journal();if(state.tab==='homework')return homeworkView();if(state.tab==='stats')return stats();return membersView()}
function feed(){return `<div class="grid"><div class="feed">${state.entries.length?state.entries.map(entryCard).join(''):'<div class="emptyCard">No practice entries yet. Be first 👀</div>'}</div><aside class="rightcol">${homeworkPanel()}${leader()}</aside></div>`}
function entryCard(e){return `<article class="entryCard"><div class="entryHead"><div class="avatar">${esc((e.display_name||'M')[0])}</div><div><strong>${esc(e.display_name)}</strong><span>${new Date(e.created_at).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</span></div><div class="duration">◷ ${fmtMin(e.duration_minutes)}</div></div><div class="flairs">${(e.categories||[]).map(c=>`<span class="flair ${CATS[c]?.[1]||''}">${esc(CATS[c]?.[0]||c)}</span>`).join('')}</div><p class="desc">${esc(e.description)}</p><div class="split"><div><small>IMPROVEMENTS</small><p>${esc(e.improvements||'—')}</p></div><div><small>CHALLENGES</small><p>${esc(e.challenges||'—')}</p></div></div><div class="entryFoot"><span class="${e.homework_completed?'done':'pending'}">✓ Homework ${e.homework_completed?'completed':'pending'}</span><div class="social"><button class="react" data-id="${e.id}">🔥 ${e.reactions||0}</button><button class="comment" data-id="${e.id}">▢ ${e.comments||0}</button></div></div></article>`}
function homeworkPanel(){return `<section class="panel"><div class="panelTitle"><b>Homework</b>${state.user?'<button id="addHomework">+ Add</button>':''}</div>${state.homework.length?state.homework.slice(0,4).map(h=>`<label class="hw"><input class="hwcheck" data-id="${h.id}" type="checkbox" ${h.completed?'checked':''}><span><strong>${esc(h.title)}</strong><small>Due ${new Date(h.due_date+'T00:00:00').toLocaleDateString()}</small></span></label>`).join(''):'<p class="muted">Nothing due.</p>'}</section>`}
function leader(){let s={};state.entries.forEach(e=>s[e.display_name]=(s[e.display_name]||0)+e.duration_minutes);return `<section class="panel"><div class="panelTitle"><b>Practice ranking</b></div>${Object.entries(s).sort((a,b)=>b[1]-a[1]).slice(0,5).map(([n,m],i)=>`<div class="rank"><span>${i+1}</span><b>${esc(n)}</b><em>${(m/60).toFixed(1)}h</em></div>`).join('')||'<p class="muted">No practice logged yet.</p>'}</section>`}
function journal(){let mine=state.entries.filter(e=>e.user_id===state.user?.id);let mins=mine.reduce((a,b)=>a+b.duration_minutes,0);return `<div class="single"><div class="metricRow">${metric('Entries',mine.length)}${metric('Practice time',(mins/60).toFixed(1)+'h')}${metric('Current streak',streak(mine)+' days')}</div><div class="feed">${mine.map(entryCard).join('')||'<div class="emptyCard">Your journal is empty.</div>'}</div></div>`}
function homeworkView(){return `<div class="single"><div class="sectionHead"><h2>Weekly Homework</h2><button class="secondary" id="addHomework">＋ Add homework</button></div>${state.homework.map(h=>`<div class="homeworkRow"><input class="hwcheck" data-id="${h.id}" type="checkbox" ${h.completed?'checked':''}><div><b>${esc(h.title)}</b><span>Due ${new Date(h.due_date+'T00:00:00').toLocaleDateString()}</span></div><em>${h.completed?'Complete':'To do'}</em></div>`).join('')||'<div class="emptyCard">No homework has been added.</div>'}</div>`}
function metric(l,v){return `<div class="metric"><span>${l}</span><strong>${v}</strong></div>`}
function streak(entries){let days=new Set(entries.map(e=>new Date(e.created_at).toDateString())),n=0,d=new Date();while(days.has(d.toDateString())){n++;d.setDate(d.getDate()-1)}return n}
function stats(){let mine=state.entries.filter(e=>e.user_id===state.user?.id),mins=mine.reduce((a,b)=>a+b.duration_minutes,0),done=state.homework.filter(h=>h.completed).length,comp=state.homework.length?Math.round(done/state.homework.length*100):0;let recent=[...mine].slice(0,12).reverse();let max=Math.max(1,...recent.map(e=>e.duration_minutes));return `<div class="single"><div class="metricRow">${metric('Total practice',(mins/60).toFixed(1)+'h')}${metric('Homework',comp+'%')}${metric('Practice streak',streak(mine)+' days')}</div><section class="chartCard"><p class="eyebrow">PRACTICE TIME</p><h2>Recent sessions</h2><div class="bars">${recent.map((e,i)=>`<div><span style="height:${Math.max(8,e.duration_minutes/max*100)}%"></span><small>${i+1}</small></div>`).join('')}</div></section><section class="chartCard"><p class="eyebrow">CATEGORY FOCUS</p><div class="categoryStats">${Object.entries(CATS).map(([k,v])=>{let n=mine.filter(e=>(e.categories||[]).includes(k)).length;return `<div><span>${v[0]}</span><div><i style="width:${mine.length?Math.round(n/mine.length*100):0}%"></i></div><b>${n}</b></div>`}).join('')}</div></section></div>`}
function membersView(){return `<div class="memberGrid">${state.members.map(m=>`<div class="memberCard"><div class="avatar large">${esc((m.display_name||'M')[0])}</div><h3>${esc(m.display_name)}</h3><p>@${esc(m.username)} · ${esc(m.role)}</p></div>`).join('')}<div class="memberCard invite"><b>Invite code</b><strong>${esc(state.group?.invite_code||'')}</strong><button id="copyCode">Copy</button></div></div>`}
function bind(){$$('.nav').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;render()});$('#signin')?.addEventListener('click',authModal);$('#signin2')?.addEventListener('click',authModal);$('#signout')?.addEventListener('click',async()=>{try{if(getToken())await rpc('o2_logout',{p_token:getToken()})}catch{}clearSession();render()});$('#newEntry')?.addEventListener('click',entryModal);$('#createGroup')?.addEventListener('click',createGroupModal);$('#joinGroup')?.addEventListener('click',joinGroupModal);$$('#addHomework').forEach(b=>b.addEventListener('click',homeworkModal));$$('.hwcheck').forEach(x=>x.onchange=()=>toggleHW(x.dataset.id,x.checked));$$('.react').forEach(b=>b.onclick=()=>react(b.dataset.id));$$('.comment').forEach(b=>b.onclick=()=>commentModal(b.dataset.id));$('#copyCode')?.addEventListener('click',()=>{navigator.clipboard.writeText(state.group.invite_code);toast('Invite code copied')})}
function modal(html){$('#modal').innerHTML=`<div class="overlay"><div class="modal">${html}</div></div>`;$('.close')?.addEventListener('click',()=>$('#modal').innerHTML='')}
function cleanUsername(v=''){return v.trim().toLowerCase().replace(/\s+/g,'')}
function validUsername(u){return /^[a-z0-9._-]{3,24}$/.test(cleanUsername(u))}
function authModal(){modal(`<button class="close">×</button><p class="eyebrow">O2 ACCOUNT</p><div class="authTabs"><button id="tabLogin" class="authTab active">Sign in</button><button id="tabSignup" class="authTab">Create account</button></div><div id="signupName" style="display:none"><label>Display name<input id="aname" autocomplete="name" placeholder="Jeremy"></label></div><label>Username<input id="auser" autocomplete="username" placeholder="jeremy" maxlength="24"></label><label>Password<input id="apass" type="password" autocomplete="current-password" minlength="6"></label><button id="authGo" class="primary wide">Sign in</button><p class="muted authHint">No email is used. Usernames use 3–24 letters, numbers, dots, underscores or hyphens.</p><p id="amsg" class="muted"></p>`);let mode='login';const msg=$('#amsg'),go=$('#authGo');const setMode=m=>{mode=m;$('#tabLogin').classList.toggle('active',m==='login');$('#tabSignup').classList.toggle('active',m==='signup');$('#signupName').style.display=m==='signup'?'block':'none';go.textContent=m==='signup'?'Create account':'Sign in';msg.textContent=''};$('#tabLogin').onclick=()=>setMode('login');$('#tabSignup').onclick=()=>setMode('signup');go.onclick=async()=>{let username=cleanUsername($('#auser').value),password=$('#apass').value,displayName=$('#aname')?.value.trim()||username;if(!validUsername(username)){msg.textContent='Username must be 3–24 characters using letters, numbers, ., _ or -.';return}if(password.length<6){msg.textContent='Password must be at least 6 characters.';return}go.disabled=true;msg.textContent=mode==='signup'?'Creating account…':'Signing in…';try{const d=mode==='signup'?await rpc('o2_register',{p_username:username,p_password:password,p_display_name:displayName}):await rpc('o2_login',{p_username:username,p_password:password});localStorage.setItem(TOKEN_KEY,d.token);localStorage.setItem(USER_KEY,JSON.stringify(d.user));state.user=d.user;$('#modal').innerHTML='';toast(mode==='signup'?'Account created':'Signed in');await refresh()}catch(e){msg.textContent=e.message}finally{go.disabled=false}}}
function createGroupModal(){modal(`<button class="close">×</button><p class="eyebrow">NEW GROUP</p><h2>Create your team</h2><label>Group name<input id="gname" placeholder="O2 Team A"></label><button id="gcreate" class="primary wide">Create group</button>`);$('#gcreate').onclick=async()=>{try{await rpc('o2_create_group',{p_token:getToken(),p_name:$('#gname').value});$('#modal').innerHTML='';toast('Group created');await refresh()}catch(e){toast(e.message)}}}
function joinGroupModal(){modal(`<button class="close">×</button><p class="eyebrow">JOIN GROUP</p><h2>Enter invite code</h2><label>Invite code<input id="gcode" placeholder="ABC123" autocomplete="off"></label><button id="gjoin" class="primary wide">Join group</button>`);$('#gjoin').onclick=async()=>{try{await rpc('o2_join_group',{p_token:getToken(),p_invite_code:$('#gcode').value});$('#modal').innerHTML='';toast('Joined group');await refresh()}catch(e){toast(e.message)}}}
function entryModal(){modal(`<button class="close">×</button><p class="eyebrow">NEW PRACTICE ENTRY</p><h2>Log today’s practice</h2><label>Practice duration (minutes)<input id="duration" type="number" min="1" max="1440" value="60"></label><label>What did you work on?</label><div class="selectFlairs">${Object.entries(CATS).map(([k,v])=>`<button class="flair ${v[1]}" data-cat="${k}">${v[0]}</button>`).join('')}</div><label>What did you actually work on?<textarea id="description" placeholder="Describe the session…"></textarea></label><div class="two"><label>Improvements<textarea id="improvements"></textarea></label><label>Challenges to overcome<textarea id="challenges"></textarea></label></div><label class="check"><input id="hwdone" type="checkbox"> I completed this week’s homework</label><button id="publish" class="primary wide">Publish entry</button>`);let selected=[];$$('.selectFlairs .flair').forEach(b=>b.onclick=()=>{let c=b.dataset.cat;b.classList.toggle('selected');selected=selected.includes(c)?selected.filter(x=>x!==c):[...selected,c]});$('#publish').onclick=async()=>{try{await rpc('o2_add_entry',{p_token:getToken(),p_duration:+$('#duration').value||0,p_description:$('#description').value,p_improvements:$('#improvements').value,p_challenges:$('#challenges').value,p_categories:selected,p_homework_completed:$('#hwdone').checked});$('#modal').innerHTML='';toast('Practice entry published');await refresh()}catch(e){toast(e.message)}}}
function homeworkModal(){modal(`<button class="close">×</button><p class="eyebrow">GROUP HOMEWORK</p><h2>Add homework</h2><label>Task<input id="htitle" placeholder="Send practice video to teacher"></label><label>Due date<input id="hdate" type="date"></label><button id="hadd" class="primary wide">Add for everyone</button>`);$('#hadd').onclick=async()=>{try{await rpc('o2_add_homework',{p_token:getToken(),p_title:$('#htitle').value,p_due_date:$('#hdate').value||null});$('#modal').innerHTML='';toast('Homework added');await refresh()}catch(e){toast(e.message)}}}
async function toggleHW(id,done){try{await rpc('o2_set_homework',{p_token:getToken(),p_homework_id:id,p_completed:done});await refresh()}catch(e){toast(e.message)}}
async function react(id){try{await rpc('o2_toggle_reaction',{p_token:getToken(),p_entry_id:id,p_emoji:'🔥'});await refresh()}catch(e){toast(e.message)}}
function commentModal(id){modal(`<button class="close">×</button><p class="eyebrow">COMMENT</p><h2>Add a comment</h2><textarea id="commentBody" placeholder="Write something supportive…"></textarea><button id="commentGo" class="primary wide">Post comment</button>`);$('#commentGo').onclick=async()=>{try{await rpc('o2_add_comment',{p_token:getToken(),p_entry_id:id,p_body:$('#commentBody').value});$('#modal').innerHTML='';toast('Comment posted');await refresh()}catch(e){toast(e.message)}}}
boot();
